### ISSUE TITLE
Spelling mistake: bilinear instead of biliniear

### ISSUE THREAD

**Issue by lehni** [LinusU/resize-image-data#3]
Title says it all ;)

**Comment by LinusU** [comment]
Whoops, PR welcome!

The function must still accept the old name as well, but all the docs should be updated to use the correct spelling ☺️

**Comment by lehni** [comment]
I'm not using the library, just noticed this when testing something, and thought I should point it out. So I won't be finding the time to create the PR…

**Comment by LinusU** [comment]
Fixed in 2b9d1f59cc7adf30f53156cdca3ecf217e64d8dd, released in [🚢 0.3.1 / 2021-10-27](https://github.com/LinusU/resize-image-data/releases/tag/v0.3.1)
